"""empty message

Revision ID: 43648d449d80
Revises: f644e1a32daf
Create Date: 2020-01-16 19:29:46.083572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43648d449d80'
down_revision = 'f644e1a32daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destination', 'zip_code')
    op.drop_column('destination', 'street')
    op.drop_column('destination', 'country')
    op.drop_column('destination', 'province')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destination', sa.Column('province', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('destination', sa.Column('country', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('destination', sa.Column('street', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('destination', sa.Column('zip_code', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
