"""empty message

Revision ID: b7ac47236817
Revises: 
Create Date: 2020-01-15 04:34:52.599707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7ac47236817'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactiondetail')
    op.add_column('cart', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('cart', sa.Column('total_item', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('total_item_price', sa.Integer(), nullable=True))
    op.alter_column('cart', 'cart_status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('cart', 'shipping_cost',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('cart', 'total_weight',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.drop_constraint('cart_ibfk_2', 'cart', type_='foreignkey')
    op.drop_column('cart', 'email')
    op.drop_column('cart', 'product_id')
    op.drop_column('cart', 'price')
    op.drop_column('cart', 'url_photo')
    op.drop_column('cart', 'product_name')
    op.drop_column('cart', 'category')
    op.drop_column('cart', 'quantity')
    op.add_column('destination', sa.Column('city_name', sa.String(length=255), nullable=True))
    op.add_column('destination', sa.Column('city_type', sa.String(length=255), nullable=True))
    op.add_column('destination', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('destination', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destination', sa.Column('city', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('destination', 'status')
    op.drop_column('destination', 'city_type')
    op.drop_column('destination', 'city_name')
    op.add_column('cart', sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('cart', sa.Column('category', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('cart', sa.Column('product_name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('cart', sa.Column('url_photo', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('cart', sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('cart', sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
    op.create_foreign_key('cart_ibfk_2', 'cart', 'product', ['product_id'], ['id'])
    op.alter_column('cart', 'total_weight',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('cart', 'shipping_cost',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('cart', 'cart_status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('cart', 'total_item_price')
    op.drop_column('cart', 'total_item')
    op.drop_column('cart', 'status')
    op.create_table('transactiondetail',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cart_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name='transactiondetail_ibfk_2'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='transactiondetail_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
