"""empty message

Revision ID: f2bf56f6f03f
Revises: b7ac47236817
Create Date: 2020-01-15 04:37:53.324176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2bf56f6f03f'
down_revision = 'b7ac47236817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('total_price', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('total_weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'total_weight')
    op.drop_column('cart', 'total_price')
    # ### end Alembic commands ###
